--- #YAML:1.0
name:                Math-Polygon
version:             1.00
abstract:            Polygon calculations
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Math::Trig:                    0
    Scalar::Util:                  1.13
    Test::More:                    0.47
    Test::Pod:                     1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
